version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "4000:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
